sudo: true
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - pypy

cache:
    apt: true
    pip: true
    directories:
        - $HOME/download-cache

addons:
    apt_packages:
        - binutils
        - default-jdk
        - gdal-bin
        - libgdal1h
        - libgeos-c1
        - libproj-dev
        - libxapian22
        - python-xapian
        - wajig

before_install:
    - mkdir -p $HOME/download-cache
    - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    - >
      if [[ $VERSION_ES == '>=5.0.0,<6.0.0' ]]; then
        echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-5.x.list
      elif [[ $VERSION_ES == '>=2.0.0,<3.0.0' ]]; then
        echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
      else
        echo "deb http://packages.elastic.co/elasticsearch/1.7/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-1.7.list
      fi
    - sudo apt-get update
    - sudo apt-get -y install oracle-java8-installer elasticsearch
    - sudo service elasticsearch restart

install:
    - pip install --upgrade setuptools
    - pip install requests "Django${DJANGO_VERSION}" "elasticsearch${VERSION_ES}"
    - python setup.py clean build install

script:
    - python setup.py test

env:
    matrix:
        - DJANGO_VERSION=">=2.2,<3.0" VERSION_ES=">=1.0.0,<2.0.0"
        - DJANGO_VERSION=">=2.2,<3.0" VERSION_ES=">=2.0.0,<3.0.0"
        - DJANGO_VERSION=">=2.2,<3.0" VERSION_ES=">=5.0.0,<6.0.0"

        - DJANGO_VERSION=">=3.0,<3.1" VERSION_ES=">=1.0.0,<2.0.0"
        - DJANGO_VERSION=">=3.0,<3.1" VERSION_ES=">=2.0.0,<3.0.0"
        - DJANGO_VERSION=">=3.0,<3.1" VERSION_ES=">=5.0.0,<6.0.0"

        - DJANGO_VERSION=">=3.1,<3.2" VERSION_ES=">=1.0.0,<2.0.0"
        - DJANGO_VERSION=">=3.1,<3.2" VERSION_ES=">=2.0.0,<3.0.0"
        - DJANGO_VERSION=">=3.1,<3.2" VERSION_ES=">=5.0.0,<6.0.0"

matrix:
    allow_failures:
        - python: 'pypy'

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: CraveFood
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: CraveFood/django-haystack-elasticsearch
    condition: $TOXENV == py27
